name: Terraform AWS ECR Setup

on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      content:
        description: 'Enter the content for ECR file'
        required: true
        default: 'World'
        
#AWS ECR Setup        
jobs:
  htmlTesting:
    name: Terraform ECR Deployment
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Login into AWS
        uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-east-1
          